# Exceed a Container's memory limit
#     A Container can exceed its memory request if the Node has memory available. But a Container is not allowed to use more than its memory limit. 
# If a Container allocates more memory than its limit, the Container becomes a candidate for termination. If the Container continues to consume memory beyond its limit, 
# the Container is terminated.

# In the args section of the configuration file, you can see that the Container will attempt to allocate 250 MiB of memory, which is well above the 100 MiB limit.
apiVersion: v1
kind: Pod
metadata:
  name: mem-demo-2
  namespace: mem-example
spec:
  containers:
    - name: mem-demo-2
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]