# Specify a memory request that is too big for your Nodes
#     Memory requests and limits are associated with Containers, but it is useful to think of a Pod as having a memory request and limit. 
#The memory request for the Pod is the sum of the memory requests for all the Containers in the Pod. Likewise, the memory limit for the Pod 
#is the sum of the limits of all the Containers in the Pod.

#Pod scheduling is based on requests. A Pod is scheduled to run on a Node only if the Node has enough available memory to satisfy the Pod's memory reques.
#In this exercise, you create a Pod that has a memory request so big that it exceeds the capacity of any Node in your cluster.
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-3-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "1000Gi"
      limits:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]