apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: alpine
          command: ['sh','-c','while true; do echo "logging" >> /opt/logs.txt; sleep 5; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      
      initContainers:
        - name: logshipper
          image: alpine
          restartPolicy: Always
          command: ['sh','-c','tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}