apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-deployment-manager
  namespace: staging
subjects:
- kind: User
  name: engineer
roleRef:
  kind: ClusterRole         # ✅ Note: Using ClusterRole here
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io

