apiVersion: v1
kind: Pod
metadata:
  name: command-demo-2
spec:
  containers:
    - name: command-demo-container-2
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: OnFailure
