#This example shows how to securely inject sensitive data, such as passwords and encryption keys, into Pods
#Create a Pod that has access to the secret data through a Volume 

#------<< kubectl create secret generic test-secret --from-literal='username=my-app' --from-literal='password=39528$vdg7Jb' >>

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret


#Each key in the Secret data map becomes a file name in this directory