apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-app
  name: web-app
spec:
  containers:
  - command:
    - sleep
    - "3200"
    image: busybox
    name: web-app
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
