# admin‑frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
      - name: admin-app
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: frontend-admin
  ports:
    - port: 80
      targetPort: 8080
