# order‑service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  namespace: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
      - name: order-app
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: order-svc
  ports:
    - port: 80
      targetPort: 8080
