# report‑service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-svc
  namespace: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: report-svc
  template:
    metadata:
      labels:
        app: report-svc
    spec:
      containers:
      - name: report-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: report-svc
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: report-svc
  ports:
    - port: 80
      targetPort: 8080
